---
format:
  pdf:
    include-in-header: 
      - text: |
          \input{SOP Formatting/PDF Formatting Script.tex}
highlight-style: ../../_styles/idle-fingers-light.theme
bibliography: references.bib
csl: ../nature.csl
---

\clearpage
\null
\thispagestyle{empty}
\newpage
\setcounter{page}{1}

The purpose of this document is to outline the contents and ongoing maintenance procedure of the **AI Resources** website.

**Developer:** Shelby Golden, M.S.

**Authors:**

- Shelby Golden, M.S.

**Date Effective:** May 22<sup>nd</sup>, 2026

**Date Updated:** May 26<sup>th</sup>, 2026


\tableofcontents
\newpage

# Important Links

- [Website](https://ysph-dsde.github.io/ai-resources-page/)
- [GitHub Repository](https://github.com/ysph-dsde/ai-resources-page)
- [SharePoint](https://yaleedu.sharepoint.com/sites/DSDEIntiativeCore/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FDSDEIntiativeCore%2FShared%20Documents%2FGeneral%2FMedia%20%26%20Communications%2FWebsite%2FAI%20Resources) (located in "DSDE - Core/General/Media & Communications/Website/AI Resources")

The project SharePoint folder contains additional resources, including running meeting notes, Excel documents tracking the listing queue for approvals and site updates, and links to surveys. This codebase includes local-only files that each user must download and place in their cloned copy of the repository in order to run the website.

# Codebase Overview

## File Structure

\vspace{-2ex}

\begin{flushleft}
\texttt{ai-resources-page/}\\
\texttt{\ \ |- \_extensions/}\\
\texttt{\ \ \ \ |- parse-latex/}\\
\texttt{\ \ \ \ |- tarleb/}\\
\texttt{\ \ \ \ \ \ |- parse-latex/}\\
\texttt{\ \ |- \_includes/}\\
\texttt{\ \ |- \_site/}\\
\texttt{\ \ |- \_styles/}\\
\texttt{\ \ \ \ |- Yale\_typeface/}\\
\texttt{\ \ |- Code/}\\
\texttt{\ \ \ \ |- Listing\_About-Us/}\\
\texttt{\ \ \ \ |- Listing\_Resources/}\\
\texttt{\ \ \ \ |- Standard Operating Procedure (SOP)/}\\
\texttt{\ \ \ \ \ \ |- SOP Formatting/}\\
\texttt{\ \ |- Data/}\\
\texttt{\ \ |- Images/}\\
\texttt{\ \ \ \ |- DSDE Identity/}\\
\texttt{\ \ \ \ |- People/}\\
\texttt{\ \ |- KEEP LOCAL/}\\
\texttt{\ \ |- Pages/}\\
\texttt{\ \ |- renv/}
\end{flushleft}

:::{.callout-note}
Files within the "KEEP LOCAL/Archived Pages/" directory are not documented here, as they are not actively utilized in the CI/CD pipeline. They are maintained for archival purposes only.
:::

## Environment Reproducibility

This website was created using R (v 4.5.2) in the RStudio IDE (v 2026.01.1+403) and Quarto (v 1.8.27). The `renv()` package (v 1.1.7) is included to reproduce the same coding environment, ensuring all relevant packages and package versions are stored. If you encounter issues running the scripts, please check that the environment is initialized and that you are using the same versions of R, RStudio, and Quarto.

\vspace{1ex}

:::{.callout-warning}
Updating packages, R, or Quarto may introduce compatibility issues with legacy code that will need to be resolved on a case-by-case basis.
:::

\vspace{1ex}

If this is the first time the repository is being initialized, you may need to initialize the environment. This step will install all packages and versions used in the codebase, ensuring a reproducible coding environment. To do so:

1. In the command-line application (i.e., Terminal for Macs or Git Bash for Windows) navigate to the codebase file location.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{cd} \str{"FILE-PATH/ai-resources-page/"}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

2. Launch the project by opening the `*.Rproj` file in RStudio.

3. In the R console, activate the environment by running the following lines of code:

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
    \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{renv::init()}      \com{# Initialize the project.}
\func{renv::restore()}   \com{# Download packages and their version saved in the lockfile.}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

:::{.callout-note}
If you are asked to update packages, say no. The `renv()` is intended to recreate the same environment under which the project was created, making it reproducible. You are ready to proceed when running `renv::restore()` gives the output:

\vspace{1ex}
\noindent\rule[0.3ex]{\textwidth}{1pt}\vspace{0ex}
\small \textbf{RStudio Console} \normalsize\vspace{0ex}
\noindent\rule[0.3ex]{\textwidth}{0.4pt}\vspace{-0.5ex}

```{.bash}
- The library is already synchronized with the lockfile.
```

\vspace{-2.5ex}
\noindent\rule[0.3ex]{\textwidth}{0.4pt}
\vspace{1ex}

If you experience any trouble with this step, you might want to confirm that you are using R (v 4.5.2) in the RStudio IDE (v 2026.01.1+403) and Quarto (v 1.8.27). You can also read more about `renv()` in their [vignette](https://rstudio.github.io/renv/articles/renv.html)\ [@renv_intro].
:::

## Ignored Files

Some project documents, scripts, and files are not distributed on GitHub or tracked by Git. Many of these are stored in `**/KEEP LOCAL/` directories or are explicitly listed under the "Project-Specific Exclusions" section of the `.gitignore` file.

Some of these files are available on the project SharePoint, while others are user-specific and do not need to be shared. If there are local-only files for this project, they will be added to the "Codebase Local Only Files" directory. This directory will contain a `README.rtf` file specifying the intended filepath for each file.

The YaleNew typeface must be downloaded directly by the user and requires NetID access: [Yale Typefaces](https://yaleidentity.yale.edu/core-identity-elements/yale-typefaces). This typeface is only used by `SOP.qmd`. Place the downloaded files in `_styles/`.


# Content Curation

## Policies

Curations are added directly to the "Pages/policies.qmd" file.

## Courses and Education Programs Curation

The courses and educational programs curation is maintained in "Curated Educational Resources.xlsx". These represent Yale University-wide courses, lecture materials, seminars, fellowships, workshops, symposia, or similar offerings.

1. Identify new candidate courses or educational programs not already listed in the "Courses & Events" sheet of "Curated Educational Resources.xlsx". Candidates may also be submitted through the suggestion box Qualtrics survey or via direct contact.

2. Fill in all required fields (columns F through W) and any relevant optional or extended classifier fields (e.g., Institutional Home: "Other"). Required fields will be highlighted in red if left blank.

3. When adding content to the "Courses & Events" sheet of "Curated Educational Resources.xlsx", initially set column V to "No". This will highlight the row in blue, indicating that it needs to be added to the website.

4. Columns B through D are used to manage listings with expiration dates. Use columns B and C to indicate the expiration tracking method and timing, and column D to override expiration dating.

## AI Tools Curation

The AI Tools tables are revised based on tools that are popular, frequently used, or listed in other Yale-affiliated curations. Curations are added directly to the "Pages/tools.qmd" file.

## Committee Review of the Curation List

No procedure is defined.

# Maintaining the Website

Page content is managed through the corresponding `*.qmd` files. Refer to existing files for guidance on content organization and formatting conventions.

## Feedback and Suggestion Box

A user feedback survey (Microsoft Forms) and suggestion box (Qualtrics) have been created for this resource, with links available on the project SharePoint. Note that only designated collaborators have editing access to both. To edit the suggestion box, access it directly in Qualtrics rather than via the external link.

On the site, these are linked in three locations: a pop-up referenced in the `*.qmd` header YAML section, the main menu bar, and the right corner of the footer.

\footnotesize \textbf{a. Configuring Stable Links} \normalsize

1. Launch the project by opening the `*.Rproj` file in RStudio.

2. Both stable links are accessible through the site's `_quarto.yml`. Open this `*.yml` file in RStudio.

3. Edit the main menu links under the `navbar:` section and the footer links under the `right:` subsection of `page-footer:` and save.

4. **OPTIONAL:** Preview the changes using a local preview. Navigate to the codebase directory in the command-line application (Terminal for Mac or Git Bash for Windows).

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{cd} \str{"FILE-PATH/ai-resources-page/"}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

6. Run a local preview of the website. It will open in a browser at the "localhost:[port]/web/" address.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} preview
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

7. To reflect changes saved in the `*.yml` file in the local preview, save a minor change in any `*.qmd` file to refresh the page. Be sure to revert these changes once the `*.yml` has been updated.

\footnotesize \textbf{b. Configuring Pop-Up Links} \normalsize

The pop-up is coordinated using "Code/popup.js" and "_includes/feedback_popup.html", a before head file.

1. Launch the project by opening the `*.Rproj` file in RStudio.

2. Open "_includes/feedback_popup.html" to update the links and pop-up copy, then save the file.

3. **OPTIONAL:** Preview the changes using a local preview. Navigate to the codebase directory in the command-line application (Terminal for Mac or Git Bash for Windows).

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{cd} \str{"FILE-PATH/ai-resources-page/"}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

4. Run a local preview of the website. It will open in a browser at the "localhost:[port]/web/" address.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} preview
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

5. To reflect changes saved in the `*.yml` file in the local preview, save a minor change in a `*.qmd` file where the pop-up will appear to refresh the page. Be sure to revert these changes once the `*.yml` has been updated.

    \begin{callout-note}[Timed Delay]
    The pop-up has a 2-minute delay. Allow the previewed page to sit for a few minutes before the pop-up appears.
    \end{callout-note}


## Index and About Us

These pages do not require regular updates or maintenance. Links and copy can be revised directly in the respective HTML or Markdown sections. To update the People section of About Us, refer to the section on maintaining Listings.

## Policies

As new sources of Yale or applicable AI-related policies are posted or released, links and copy can be revised directly in the respective HTML or Markdown sections.

## AI Tools

The AI Tools page has two sections: links to frequently visited or other Yale-affiliated curation lists, and tables summarising popular AI tools used across different applications. Links and copy can be revised directly in the respective HTML or Markdown sections.

## Listing Pages

Two pages utilize the Quarto Listing feature: the Courses and Educational Programs filter/search page and the People section of the About Us page. Both of these pages or sections is comprised of the following files:

- `*.qmd` — Renders the page on the website.
- `*.yml` — Contains all information fields and organizes them within defined hierarchies and classifications.
- `*.ejs` — Ingests the `*.yml` file and processes it through embedded HTML and JavaScript, formatting the tiles and defining page behaviors such as content-responsive text clamping and the "Show More" button.
- `*.scss` — Defines custom styling and some responsive behaviors.

The `*.qmd` files are located with in the "Pages/" directory, the `*.yml` and and `*.ejs` are in "Code/Listing_\*/" respective directory, and the `*.scss` file is in the "\_styles/" directory. Users only need to edit the `*.yml` to remove, add, or update existing content fields.

### Adding Tiles

1. In the command-line application (i.e., Terminal for Macs or Git Bash for Windows) navigate to the codebase file location.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{cd} \str{"FILE-PATH/ai-resources-page/"}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

2. Run a local preview of the website. It will open in a browser at the "localhost:[port]/web/" address.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} preview
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

3. Launch the project by opening the `*.Rproj` file in RStudio.

4. Open the `*.yml` and `*.qmd` files associated with the Listing you want to revise.

5. The header of each `*.yml` file describes the required and optional fields used by the respective `*.ejs` file, as well as any additional hierarchies and classifications needed to organize the content. Refer to preexisting entries to help determine formatting and structural conventions.

    \begin{callout-note}[Banner Color Scheme]
    The tile banner randomly generates a network graph each time the page is loaded. The colour schemes applied to this JavaScript are described in the "Progress Report" sheet of "Curated Educational Resources.xlsx".
    \end{callout-note}

6. To refresh the local preview and reflect changes saved in the `*.yml`, save a minor change in the associated `*.qmd` file. Be sure to revert these changes once you have finished updating the `*.yml`.

7. Update the page-level "Date last updated: \_\_" and "Last updated by: \_\_" fields in the header section of the `*.yml` file.

8. Update column V in the "Courses & Events" sheet of "Curated Educational Resources.xlsx" to "Yes".

10. The content is now ready for publishing. This process is described below.

### Removing Tiles

1. In the command-line application (i.e., Terminal for Macs or Git Bash for Windows) navigate to the codebase file location.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{cd} \str{"FILE-PATH/ai-resources-page/"}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

2. Run a local preview of the website. It will open in a browser at the "localhost:[port]/web/" address.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} preview
  \end{Verbatim}
  \end{codebox}

  \vspace{-4.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

3. Launch the project by opening the `*.Rproj` file in RStudio.

4. Open the `*.yml` and `*.qmd` files associated with the Listing you want to revise.

5. Locate the `title` listing header for the tile to be removed. Delete all relevant components under this listing section and remove any extra spacing.

6. To refresh the local preview and reflect changes saved in the `*.yml`, save a minor change in the associated `*.qmd` file. Be sure to revert these changes once you have finished updating the `*.yml`.

7. Update the page-level "Date last updated: \_\_" and "Last updated by: \_\_" fields in the header section of the `*.yml` file.

8. Update column V in the "Courses & Events" sheet of "Curated Educational Resources.xlsx" to "Removed".

10. The content is now ready for publishing. This process is described below.

# Publishing Updates

A Shell script was created to render the site while preventing unused media from being transferred to the GitHub repository. Follow the steps below to render and publish the website.

1. Ensure all work is saved and committed.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{git} add \op{<}\str{"FILE-NAME"}\op{|}.\op{>}
\func{git} commit \atr{-m} \str{"Your message"}
\func{git} push
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

2. Render the site locally. The configuration updates the `_site` directory, which is excluded from version control by the `.gitignore` file. This process may take a few minutes to complete.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} render
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

3. Make sure the shell script is executable.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{chmod} \atr{+x} Code/copy\_images.sh
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}
  
4. Run the script.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
./Code/copy\_images.sh
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}
    
5. **OPTIONAL:** Verify that all the correct files have been rendered to the `_site` directory.
  
\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{ls} \atr{-R} \_site
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

6. If everything looks correct, publish the site. Follow the prompts by entering "Yes" to proceed with updating the site and entering any required passwords when prompted.
     
\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} publish gh-pages \kw{--no-render}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

## If Rendering Fails to Complete

The webpage may occasionally fail to publish; however, this is not necessarily a critical error. If this issue is encountered after attempting to publish, any working trees generated during the incomplete process must be cleared before re-executing the render. This is a known Quarto bug that may be resolved in a future update.

For example, if the working tree is called:

```{.bash}
FILE-PATH/.quarto/quarto-publish-worktree-17fef8679f581e08/
```

1. List all currently active worktrees in the environment. One will be associated with `quarto publish` and denoted as "prunable."

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{git} worktree list

\com{# Example Result}
\str{FILE-PATH/}  69edfb0 \op{[}main\op{]}
\str{FILE-PATH/.quarto/quarto-publish-worktree-71502552fdce11b5}  0ee5bea \op{[}gh-pages\op{]} prunable
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

2. Forcably removed the prunable worktree.

\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{git} worktree remove \kw{--force} \str{"FILE-PATH/.quarto/quarto-publish-worktree-71502552fdce11b5"}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

3. Retry publishing the site. Follow the prompts by entering "Yes" to proceed with updating the site and entering any required passwords when prompted.
     
\begin{list}{}{\setlength\leftmargin{2.5em}}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{1pt}\vspace{-2.5ex}
  \item\small \textbf{Command-Line Interface} \normalsize \vspace{-2.5ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}\vspace{-0.8ex}
  
  \begin{codebox}
  \begin{Verbatim}[breaklines = true, breaksymbol = \textcolor{idlelinnum}{\scriptsize$\hookrightarrow$}, commandchars = \\\{\}]
\func{quarto} publish gh-pages \kw{--no-render}
  \end{Verbatim}
  \end{codebox}

  \vspace{-4ex}
  \item\noindent\rule[0.3ex]{\dimexpr\textwidth - 2.5em\relax}{0.4pt}
\end{list}

# Maintaining the SOP

This Standard Operating Procedure (SOP) uses a preconfigured LaTeX formatting script. The report `*.qmd` and formatting files are located in "Code/Standard Operating Procedure (SOP)/".

If you are updating the document, please add your name to the **Authors** field and update the **Date Updated** field accordingly. The LaTeX formatting script will automatically include the date the document was rendered at the top of the page.

Indented code blocks use Verbatim code environments, which require additional formatting to align the environment and apply code highlighting. Use "Code Highlighting Formatting_Verbatim.R" to prepare code for this environment and one-level indentation.

To preview a rendered version of these documents, comment out the following line in the website's `_quarto.yml`:

\vspace{-2.5ex}
\noindent\rule[0.3ex]{\textwidth}{1pt}\vspace{-2.5ex}
\small \textbf{\texttt{\_quarto.yml}} \normalsize\vspace{-2.5ex}
\noindent\rule[0.3ex]{\textwidth}{0.4pt}\vspace{-0.8ex}

```{.yml}
- "!Code/Standard Operating Procedure (SOP)/SOP.qmd"
- "!Code/Standard Operating Procedure (SOP)/Code Highlighting Formatting_Verbatim.qmd"
```

\vspace{-5.5ex}
\noindent\rule[0.3ex]{\textwidth}{0.4pt}


This line prevents the SOP and its associated `*.qmd` files from being rendered when the site is published. Once editing and previewing are complete, uncomment the line to allow a new PDF to be rendered.

Once you have finished editing the document render it, move the resulting `*.pdf` to the project's root directory, then commit and push your changes.

# References
