---
title-block-banner: true
title: |
  AI Tools
description: |
  </br>
  AI tools have become integrated into everyday workflows and programs, with many optimized for specific tasks. Even among comparable tools, differences in performance and accessibility features make certain options better suited for particular applications.
  </br>
  </br>
  Below is a curated list of common AI tools and links to Yale-provided tools, which are free for Yale affiliates and may include additional security protections. Tools are organized by common use cases, with brief descriptions of how to best utilize them.
include-in-header: 
  - ../_includes/feedback_popup.html
toc: false
bibliography: references.bib
csl: ../Code/nature.csl
---

:::{.column-screen}

```{=html}
<body>
  <div class="container_static_page_tiles">
      <div class="tile_static_page" id="tile1">
          <canvas class="network-canvas"></canvas>
          <a href="https://ai.yale.edu/yales-ai-tools-and-resources" title="AI at Yale - Guidance">
              <div class="content">
                  <div class="text-box">
                      <h1>Yale's AI Tools and Resources</h1>
                      <p class="description">Explore AI tools available to students, faculty, and staff through comprehensive tables detailing options, access methods, and supported data types. Start experimenting to discover what works best for your needs.</p>
                  </div>
                  <h2>From AI at Yale</h2>
                  <i class="tile_icon_static bi bi-arrow-right-circle-fill"></i>
              </div>
          </a>
      </div>
      <div class="tile_static_page" id="tile2">
          <canvas class="network-canvas"></canvas>
          <a href="https://poorvucenter.yale.edu/teaching/teaching-resource-library/ai-guidance-for-teachers/ai-tools/yale-provided-tools" title="Resources page">
              <div class="content">
                  <div class="text-box">
                      <h1>Yale Provided Tools</h1>
                      <p class="description">Discover Yale's specialized AI tools including Clarity, Microsoft Copilot, and Google's Gemini. Each offers unique capabilities from conversational AI to custom quiz generation, with detailed access information and feature guides available to the Yale community.</p>
                  </div>
                  <h2>From the Poorvu Center</h2>
                  <i class="tile_icon_static bi bi-arrow-right-circle-fill"></i>
              </div>
          </a>
      </div>
      <div class="tile_static_page" id="tile3">
          <canvas class="network-canvas"></canvas>
          <a href="https://sr.ithaka.org/our-work/generative-ai-product-tracker/" title="Ithaka S+R tracker">
              <div class="content">
                  <div class="text-box">
                      <h1>Generative AI Product Tracker</h1>
                      <p class="description">Explore generative AI products designed for and actively used in higher education. From teaching tools to research applications, this regularly updated tracker helps faculty and students discover new solutions as they enter the market.</p>
                  </div>
                  <h2>From Ithaka S+R</h2>
                  <i class="tile_icon_static bi bi-arrow-right-circle-fill"></i>
              </div>
          </a>
      </div>
    </div>
    <script src="../Code/network_graph.js"></script>
</body>
```

:::

```{=html}
<body>
  <div class="table_type_header">
    <canvas class="network-canvas"></canvas>
    <div class="overlay-text">Coding</div>
  </div>

  <script src="../Code/circuit_board_texture.js"></script>
</body>
```

<table class="curation-table">
    <tr>
        <th class="tool-name"></th>
        <th class="description">Description</th>
        <th class="at-yale">Free At Yale?</th>
    </tr>
    <!-- Row 1 -->
    <tr>
        <td class="tool-name"><a href="https://ai.azure.com/">Azure AI</a></td>
        <td class="description">A comprehensive framework of AI tools created by Microsoft that provides a suite of business operational support. Offers access to over 11,000 foundational, open-source, reasoning, multimodal, and industry-specific models from providers such as DeepSeek, Meta, NVIDIA, and more. Includes standard code assistance tools with compatibility across numerous IDEs and an array of languages, integrated with Microsoft Agent Framework, LangChain, CrewAI, and LlamaIndex. Provides pre-built AI agents and features, supports development of custom MCP tools, and includes usage monitoring and governance for enhanced security, cost management, and harmful content reduction.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 2 -->
    <tr>
        <td class="tool-name"><a href="https://claude.com/product/claude-code">Claude Code</a></td>
        <td class="description">An AI tool from the Claude series designed by Anthropic and trained using Constitutional AI, offering models like Opus, Sonnet, and Haiku. Integrates with Command-Line Applications such as terminal, and IDEs including VS Code and JetBrains to support advanced code analysis, debugging, and feature implementation. Connects with other command-line tools used in software development including deployment, databases, monitoring, and version control. Securely runs locally to interact with model Application Programming Interfaces (APIs) without a backend or remote code index. Maintains user control by requesting modification approval, adapts to user-defined standards for coding practices, and builds on established Software Development Kit (SDK) and GitHub Actions.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 3 -->
    <tr>
        <td class="tool-name"><a href="https://openai.com/codex/">Codex</a></td>
        <td class="description">An AI-assisted software development tool developed by OpenAI and based on their frontier coding models and is a descendant of GPT-3. Accessible through their CLI, GitHub, and select IDEs, providing coding support for routine to complex tasks. Proposes end-to-end solutions with agent prompts to build features, resolve complex refactors, handle migration tasks, interpret code, and write documentation. Agents can work in parallel across projects or execute unprompted automations of routine tasks such as triage, alert monitoring, and Continuous Integration and Continuous Deployment (CI/CD).</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 4 -->
    <tr>
        <td class="tool-name"><a href="https://cursor.com/home">Cursor</a></td>
        <td class="description">A generative and agentic IDE plugin that enhances software development by improving code comprehension through synthesis of project information, detailed code summaries, and automated documentation creation. Includes standard code support tools such as code completion, available through its desktop IDE based on VS Code and a Command-Line Interface (CLI). Designed specifically to support software development workflows and tasks including planning, designing, debugging, Git checkpoints, and team collaboration. Supports custom domain knowledge through training, MCP integration, and plugins such as Figma, Slack, and GitHub. Users can access major models including Claude, Gemini, and GPT.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 5 -->
    <tr>
        <td class="tool-name"><a href="https://github.com/features/copilot">GitHub Copilot</a></td>
        <td class="description">A generative AI model developed by GitHub, OpenAI, and Microsoft, trained on publicly available sources including public repositories on GitHub and based on the GPT-3 architecture. Installable across numerous Integrated Development Environments (IDEs) and supporting an array of programming languages. Provides code completion, management agents for generating audits, and custom Model Context Protocol (MCP) integration. Can be trained on specific projects to become a tailored expert.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 6 -->
    <tr>
        <td class="tool-name"><a href="https://replit.com/">Replit</a></td>
        <td class="description">Based on OpenAI models like GPT-3, Replit offers a comprehensive platform that enables users to code and develop software projects, including featured tools like Ghostwriter. The platform provides various tools specifically designed for different purposes such as app development, website creation, and database integration with third-party services. Replit is created with a focus on beginners who may have little to no prior experience with programming languages or developing products as code projects. It enhances the learning experience by offering detailed explanations and tips throughout the development process. For direct coding, Replit includes standard AI-assisted features such as autocompletion and debugging assistance, making it a valuable tool for both novice and experienced developers alike.</td>
        <td class="at-yale">No</td>
    </tr>
</table>

```{=html}
<body>
  <div class="table_type_header">
    <canvas class="network-canvas"></canvas>
    <div class="overlay-text">Figure and Image Generation</div>
  </div>
</body>
```

<table class="curation-table">
    <tr>
        <th class="tool-name"></th>
        <th class="description">Description</th>
        <th class="at-yale">Free At Yale?</th>
    </tr>
    <!-- Row 1 -->
    <tr>
        <td class="tool-name"><a href="https://openai.com/index/dall-e-3/">DALL-E</a></td>
        <td class="description">A foundational transformer model using neural networks developed by OpenAI that translates text prompts into high-fidelity images. This 12-billion parameter version of GPT-3 is trained on text-image pairs, generating diverse responses including plausible combinations of unrelated concepts. Capabilities include controlling attributes, spatially orienting multiple objects, visualizing perspectives, and inferring contextual details from simple prompts. It discerns visual elements with temporal, geographical, and zoomed perspectives. OpenAI implements safety features to prevent harmful content, deepfakes through detection algorithms, and biased content. Recent iterations prevent generating content in the style of living artists and allow artists to opt out of training.</td>
        <td class="at-yale">Yes</td>
    </tr>
    <!-- Row 2
    <tr>
        <td class="tool-name"><a href="https://www.midjourney.com/home">Midjourney</a></td>
        <td class="description"></td>
        <td class="at-yale">No</td>
    </tr> -->
    <!-- Row 3
    <tr>
        <td class="tool-name"><a href="https://artlist.io/">Nano Banana</a></td>
        <td class="description"></td>
        <td class="at-yale">No</td>
    </tr> -->
</table>

```{=html}
<body>
  <div class="table_type_header">
    <canvas class="network-canvas"></canvas>
    <div class="overlay-text">Literature Review</div>
  </div>
</body>
```

<table class="curation-table">
    <tr>
        <th class="tool-name"></th>
        <th class="description">Description</th>
        <th class="at-yale">Free At Yale?</th>
    </tr>
    <!-- Row 1
    <tr>
        <td class="tool-name"><a href="ChatGPT Atlas<">ChatGPT Atlas</a></td>
        <td class="description"></td>
        <td class="at-yale">No</td>
    </tr> -->
    <!-- Row 2 -->
    <tr>
        <td class="tool-name"><a href="https://consensus.app/">Consensus</a></td>
        <td class="description">An AI-powered search engine designed to assist with directed searches and synthesis of published papers. It focuses on providing an accurate and accessible tool trusted by academic researchers and university students. The search engine sources from more than 250 million cited, peer-reviewed literature, including full-text content from leading publishers. AI responses are annotated with citations to real literature papers, allowing users to narrow matches to meet specific inclusion criteria (e.g., timeframes and study design) or compare published results on a given topic.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 3 -->
    <tr>
        <td class="tool-name"><a href="https://elicit.com/">Elicit</a></td>
        <td class="description">An AI-powered search engine designed to assist with directed searches and the synthesis of published papers. It is utilized in both academic and industry settings to curate and synthesize search results from over 138 million academic papers and 545,000 clinical trials, with content continually expanding. The engine uses semantic search approaches, alleviating the need for exact keyword searches. It allows users to fine-tune results, such as changing the papers used in reports and rerunning reports to integrate recent updates. AI responses are cited to ensure traceability and highlight the specific portions of papers used to generate those responses. The tool is user-oriented, supporting automated screening and data extraction, cataloging results for later reference, and setting up alerts for new research releases.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 4
    <tr>
        <td class="tool-name"><a href="https://gemini.google/overview/deep-research/">Gemini (Deep Research)</a></td>
        <td class="description"></td>
        <td class="at-yale">No</td>
    </tr> -->
    <!-- Row 5 -->
    <tr>
        <td class="tool-name"><a href="https://www.researchrabbit.ai/">Research Rabbit</a></td>
        <td class="description">A free AI-powered search engine designed for topic-based searches that facilitates the discovery of related papers. The search engine sources from more than 270 million academic papers and is used by researchers and institutions worldwide. Its algorithms learn from your reading and searching patterns to tailor results to your research interests, improving recommendations with each use. Notably, search results include a graphical visualization showing how paper topics are connected.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 6
    <tr>
        <td class="tool-name"><a href="https://manus.im/">Manus</a></td>
        <td class="description"></td>
        <td class="at-yale">No</td>
    </tr> -->
    <!-- Row 7 -->
    <tr>
        <td class="tool-name"><a href="https://scite.ai/">Scite</a></td>
        <td class="description">An AI-powered search engine for directed searches and synthesis of published papers. It has indexed 1.4B+ citations, partners with 30+ publishers, and includes paywalled content. The platform serves researchers, students, publishers, universities, librarians, and industry professionals worldwide. The SmartCitation feature evaluates whether citations support or contradict claims and flags retracted or disputed publications. This is available via app and browser extensions (Chrome, Firefox, Safari) that show how articles are cited online. Publishers can track how their work is mentioned, and the platform generates visualizations of citation networks.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 8 -->
    <tr>
        <td class="tool-name"><a href="https://www.semanticscholar.org/">Semantic Scholar</a></td>
        <td class="description">A free AI-powered search engine designed for directed search, synthesis, and effective reading of published papers. Search over 214 million papers across all fields of science and filter by journal, conference, topic, or "Highly Influential Citations" (identified by a machine-learning model that assesses citation count and context). Features include an in-app citation generator (MLA, APA, Chicago, BibTeX), organized libraries that generate personalized search recommendations based on user ratings, and alerts for new citations to specific papers or authors. Two notable features enhance reading: Ask This Paper provides AI-generated answers to questions about a given paper, while Semantic Reader offers content highlighting for easier skimming, personalized citation indicators for papers in your library, and TLDR (Too Long; Didn't Read) summaries of cited works for context. The Semantic Reader Project is open-source to support development of new literature search tools.</td>
        <td class="at-yale">No</td>
    </tr>
    <!-- Row 9
    <tr>
        <td class="tool-name"><a href="https://github.com/features/copilot">Undermind</a></td>
        <td class="description"></td>
        <td class="at-yale">No</td>
    </tr> -->
</table>

```{=html}
<body>
  <div class="table_type_header">
    <canvas class="network-canvas"></canvas>
    <div class="overlay-text">General Use</div>
  </div>
</body>
```

<table class="curation-table">
    <tr>
        <th class="tool-name"></th>
        <th class="description">Description</th>
        <th class="at-yale">Free At Yale?</th>
    </tr>
    <!-- Row 1 -->
    <tr>
        <td class="tool-name"><a href="https://chatgpt.com/">ChatGPT</a></td>
        <td class="description">A large language model (LLM) developed by OpenAI that interacts with users through open-ended dialogue and serves as the core model in specialized tools deployed by OpenAI and other developers. It is trained using Reinforcement Learning from Human Feedback (RLHF), similar to InstructGPT, with supervised fine-tuning and output ranking. Notable limitations include hallucinations, sensitivity to prompt variation, and inferring user meaning without asking for clarity. OpenAI continually works to improve content appropriateness, reduce biased results, and enhance usage controls with each release. They offer various tools and models designed for specific applications and domains (research, business, coding, etc.).</td>
        <td class="at-yale">Yes</td>
    </tr>
    <!-- Row 2 -->
    <tr>
        <td class="tool-name"><a href="https://claude.ai/login">Claude</a></td>
        <td class="description">An AI tool from the Claude series developed by Anthropic using Constitutional AI training, offering models like Opus, Sonnet, and Haiku with varying performance features that serve as the foundation for tools from Anthropic and other developers. Trained and fine-tuned using RLHF and supervised training aligned with Anthropic's Constitutional AI standards for helpful, honest, and harmless AI. Uses retrieval augmentation to combine trained outputs with external data. Limitations include hallucinations and latency, though stringent safeguards are implemented aligned with Constitutional AI principles. They offer various tools and models designed for specific applications and domains (research, business, coding, etc.) with integrations in workflow tools like IDEs, Microsoft 365, and web browsers.</td>
        <td class="at-yale">Yes</td>
    </tr>
    <!-- Row 3
    Removed as the site is blocked by the Yale firewall
    <tr>
        <td class="tool-name"><a href="https://deepseek.ai/">DeepSeek</a></td>
        <td class="description">Things</td>
        <td class="at-yale">No</td>
    </tr> -->
    <!-- Row 4 -->
    <tr>
        <td class="tool-name"><a href="https://gemini.google.com/">Gemini</a></td>
        <td class="description">A multimodal LLM (text, audio, images, and more) hybrid tool developed by Google for open-ended dialogue that serves as the foundation for specialized tools from Google and other developers. Trained on publicly available data filtered for appropriateness and fine-tuned with RLHF and supervised training. Uses retrieval augmentation to combine trained outputs with external data. Limitations include hallucinations, persona projection, glitches with nonsensical prompts, and presenting narrow options rather than comprehensive synthesis. Google continually works to improve content appropriateness, reduce bias, and enhance usage controls with each release. They offer various tools and models designed for specific applications and domains (creative inspiration, media generation, research, business, coding, etc.).</td>
        <td class="at-yale">Yes</td>
    </tr>
    <!-- Row 5
    <tr>
        <td class="tool-name"><a href="https://github.com/features/copilot">Grok</a></td>
        <td class="description">Things</td>
        <td class="at-yale">No</td>
    </tr> -->
    <!-- Row 6
    <tr>
        <td class="tool-name"><a href="https://github.com/features/copilot">Llama</a></td>
        <td class="description">Things</td>
        <td class="at-yale">No</td>
    </tr> -->
</table>






